//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phukien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHU
    {
        public int MADOANHTHU { get; set; }
        public System.DateTime NGAY { get; set; }
        public decimal DOANHSO { get; set; }
        public Nullable<int> MASANPHAM { get; set; }
        public string GHICHU { get; set; }

        public bool DaGiao { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
